global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'gateway'
    static_configs:
      - targets: ['gateway:8080']

  - job_name: 'auth'
    static_configs:
      - targets: ['auth:8081']

  - job_name: 'blog'
    static_configs:
      - targets: ['blog:8082']
